### ISSUE TITLE
Game crashed on version 1.3.0

### ISSUE THREAD

**Issue by Leisterredux** [LeonBlade/PaisleyPark#3] opened 2019-04-24 01:03 UTC
While updating Paisley Park from version 1.2.1 to 1.3.0, the application becomes unresponsive and can cause Final Fantasy XIV to crash.

Steps involved:

Open FFXIV
Open Paisley Park (Version 1.2.1)
Accept the update (to Version 1.3.0)
An error will appear from ffxiv_dx11.exe and the client -may- crash.
Screenshot of error is below along with error.log and output.log:
![error](https://user-images.githubusercontent.com/49928188/56625396-26044c00-660b-11e9-9e1d-2ed8a2a18333.png)
[error.log](https://github.com/LeonBlade/PaisleyPark/files/3110128/error.log)
[output.log](https://github.com/LeonBlade/PaisleyPark/files/3110129/output.log)

EDIT: Did a fresh install, previous markers work but still not able to input new presets.

**Comment by LeonBlade** [comment] 2019-04-24 01:25
Thanks for the report.  I don't really have issues when I update, but I'll rethink the update process to prevent this from happening.

**Comment by Leisterredux** [comment] 2019-04-24 23:15
Update:

Crashes only happen only when trying to use any of the presets.

Upon further testing, crashes do not happen when using the presets only in a certain maps and areas, including some dungeons and trials instances. 

However attempting to teleport out of those safe areas after using presets will result in same crash.

Character deaths (screen blacked out) will not cause crash.

This is with the latest version 1.3.1

**Comment by LeonBlade** [comment] 2019-04-25 02:59
This is a very strange error.  This has never been a situation at all until this most recent patch.  It will take me some time to investigate.

**Comment by Leisterredux** [comment] 2019-04-25 05:48
Take your time, I'll also try to do more testings. For now it works as intended inside the instances which is great. I was doing ucob tonight and the game only crashed after we finished the lockout and need to exit the instance, which is a small setback. I suspect it's either due to my PC ( which is unlikely since I have everything up to date) or the new patch.

**Comment by Trav877** [comment] 2019-04-25 06:36
Want to say that i'm having the same issue as leister, and it only ever occurs when i leave UCoB but i haven't been using it anywhere else. it happened with 1.3 and 1.31 using presets that i made myself.

**Comment by skyalteria** [comment] 2019-04-26 04:55
Also having same issue in both Ultima Weapon and UCOB. Have not tried other instances.

**Comment by celphos** [comment] 2019-04-27 05:19
I had the same issues after I left doing o12s (no crashes during raid, just as soon as I left.)  Here's the 2 logs, hopefully they'll help.

[output.log](https://github.com/LeonBlade/PaisleyPark/files/3123516/output.log)
[error.log](https://github.com/LeonBlade/PaisleyPark/files/3123517/error.log)

EDIT: the error log seems to be something unrelated to the problem and happened a couple days ago when I was testing it.

**Comment by LeonBlade** [comment] 2019-04-27 05:21
Thank you for your report.  This is confirmed for being an issue for all
users (myself included).  I'll try to find some time here soon to fix the
issue.  I have put it off longer due to the program still functioning
otherwise.

**Comment by healrsadjust** [comment] 2019-04-28 00:29
I too crash and get same error when leaveing UCoB

**Comment by MrSigy** [comment] 2019-04-30 05:39
Same issue no crash inside but upon exiting the area.
Also Nancy Host keeps outputting this error

> 2019-04-28 23:33:43.7526 Could not start Nancy host. System.Net.HttpListenerException (0x80004005): De parameter is onjuist
   bij System.Net.HttpListener.AddAllPrefixes()
   bij System.Net.HttpListener.Start()
   bij Nancy.Hosting.Self.NancyHost.TryStartListener()
   bij Nancy.Hosting.Self.NancyHost.StartListener()
   bij Nancy.Hosting.Self.NancyHost.Start()
   bij PaisleyPark.ViewModels.MainWindowViewModel.OnStartServer()
2019-04-30 07:05:23.1525 Could not start Nancy host. System.Net.HttpListenerException (0x80004005): De parameter is onjuist
   bij System.Net.HttpListener.AddAllPrefixes()
   bij System.Net.HttpListener.Start()
   bij Nancy.Hosting.Self.NancyHost.TryStartListener()
   bij Nancy.Hosting.Self.NancyHost.StartListener()
   bij Nancy.Hosting.Self.NancyHost.Start()
   bij PaisleyPark.ViewModels.MainWindowViewModel.OnStartServer()

>

**Comment by Icabbles** [comment] 2019-05-01 11:16
Getting also crashes. Some when leaving a certain area (just tested it inside T13) and in Mist
![paisleycrash](https://user-images.githubusercontent.com/29927352/57015101-4e93d380-6c13-11e9-8879-31eaf2e49554.JPG)

**Comment by donneee** [comment] 2019-05-02 06:46
i'm getting the same type of errors. Can't wait for you to fix this and figure out how to implement json commands with this in Trig for memes 

this was my test in goblet to a crash.
http://bit.ly/2ZOrI6Z

keep up the work my dude!

**Comment by Akava2005** [comment] 2019-05-02 23:15
I'm getting this error as well. It only happens when trying to leave an instance after using way markers.

Steps to Reproduce:

1. Enter an instance (UwU or The Minstrel's Ballad: Ultima's Bane)
2. Open Paisley Park v1.3.1
3. Select a preset and load it (Mine uses all Markers)
4. Remove the markers
5. Place all markers (manually or with a different preset)
6. Attempt to exit the instance

![FFXIV Error](https://user-images.githubusercontent.com/22595362/57112567-32bd2a00-6d06-11e9-8cef-56c712cf193a.PNG)

**Comment by celphos** [comment] 2019-05-03 06:04
So I did a little more messing around to see if I can create the crash in different ways, It still works amazing in duties, however I tested it in Shirogane to see if it would crash if I created a Profile there.  

If I create a profile in Shirogane and attempt to load it, it immediately crashes.  Here's the profile I used and also the error logs / output.
[House Shiro Outside.txt](https://github.com/LeonBlade/PaisleyPark/files/3140765/House.Shiro.Outside.txt)
[output.log](https://github.com/LeonBlade/PaisleyPark/files/3140766/output.log)

I also did a test with the program inside the house and it doesn't crash if I make a profile in there.
[Inside Shiro Mansion.txt](https://github.com/LeonBlade/PaisleyPark/files/3140770/Inside.Shiro.Mansion.txt)

In fact, every profile I had that normally crashes if I'm outside in Shirogane and attempt to load it did not crash while I was in the home.  I'm guessing the waymarks don't appear cause it's on a different map or too far out. 

I'm not sure if it ever worked in housing areas in previous patches but hopefully this helps solve the mystery a little.

**Comment by LeonBlade** [comment] 2019-05-05 04:03
Thank you @celphos for your testing.  Unfortunately, the logs don't help because of the nature of the crash.  If I could get information from the game it would be better, but the most we can get is a stack trace.

It's very interesting that inside a house it doesn't crash if that's what you're saying?  When you load waymarks in the house and leave it doesn't crash?  Unfortunately, I don't have time to look into this more at the moment.

It will take a long time to figure out what's wrong.  I'm sorry for the long wait to fix this error, but it's a lot more obscure than you might think.

**Comment by celphos** [comment] 2019-05-05 04:25
Sorry I mean that I can load any waymark setting inside the house and it wont crash, if I leave the house after doing so, I will crash.  I even made a waymark setting with the outside areas that crash immediately  and load those same waymarks inside the house and they wont crash.  

I'm basically just alt gearing up omega and stuff with nothing else to do so I'll keep looking around in areas to see what crashes and what doesn't if that helps?

There's no need to apologize for the delays, as Leis said, take your time.

**Comment by LeonBlade** [comment] 2019-05-05 06:16
It doesn't really matter what you load in, it matters if you crash or not
when you transfer areas.

**Comment by Kurtty5878** [comment] 2019-05-07 18:25
I am having the same issue as celphos stated. Anytime I teleport or enter any housing ward it crashes. Tried it in Ul'dah and it worked fine, teleported to my house and it crashed as soon as the load screen started,

**Comment by LeonBlade** [comment] 2019-05-07 18:27
@Kurtty5878 Thanks!  I just confirmed this today myself and thought it was a new issue.  I'm currently looking into a new method of placing waymarks to avoid this issue.

Thank you everyone for submitting your experiences with this issue.

**Comment by Surged28** [comment] 2019-05-10 01:40
I have the issue as well but the odd part is I still crash even if I close the program before leaving the duty.

**Comment by Jyntax** [comment] 2019-05-10 22:37
> 
> 
> I have the issue as well but the odd part is I still crash even if I close the program before leaving the duty.

That's because the Injection of Data is still in the game. It's not the programm that crashed the game but the injected Code which the game can't handle for some reason. Correct me if I'm wrong.

**Comment by LeonBlade** [comment] 2019-05-11 00:20
> > I have the issue as well but the odd part is I still crash even if I close the program before leaving the duty.
> 
> That's because the Injection of Data is still in the game. It's not the programm that crashed the game but the injected Code which the game can't handle for some reason. Correct me if I'm wrong.

The game will crash regardless of if you close it or not.  Once you place a waymark with Paisley Park, no matter what you do, it will crash the game when you leave the zone.

**Comment by Kurtty5878** [comment] 2019-05-15 14:20
I get this error when trying to update.

![2019-05-15 (2)](https://user-images.githubusercontent.com/50379020/57782716-6a5aa780-76f2-11e9-838a-7a5b463952ed.png)

**Comment by Jyntax** [comment] 2019-05-15 16:42
Since the Update to 1.3.3 it doesn't crash on teleportation/leaven the area anymore. It crashes like 2-3 seconds after I press load to load a preset.

**Comment by LeonBlade** [comment] 2019-05-15 19:29
Does anything pop up?  @Jyntax 

@Kurtty5878 That sounds unrelated to this issue.  Try downloading a new release.  Make sure you're running in admin mode as well.  You can upload your error log as well.

**Comment by Kurtty5878** [comment] 2019-05-15 20:20
It's the most recent release. 1.3.1 works but when I go to update it it gives me that error. It runs in admin by default. The files are all located in the same folder.

**Comment by LeonBlade** [comment] 2019-05-15 20:22
> It's the most recent release. 1.3.1 works but when I go to update it it gives me that error. It runs in admin by default. The files are all located in the same folder.

Your antivirus could be triggering it.  Just download the new release manually here: https://github.com/LeonBlade/PaisleyPark/releases/download/v1.3.3/PaisleyPark.zip

**Comment by Kurtty5878** [comment] 2019-05-15 20:38
Looks like it was the antivirus. Idk how this stuff works, but why did a previous version work fine and this one had issue?

**Comment by LeonBlade** [comment] 2019-05-15 20:38
> Looks like it was the antivirus. Idk how this stuff works, but why did a previous version work fine and this one had issue?

Not sure.  I'm glad it works for you though!

**Comment by LeonBlade** [comment] 2019-05-16 04:06
Thank you everyone for submitting feedback on this bug.  It's now fixed in 1.3.4!

**Closed as completed by LeonBlade** 2019-05-16 04:06 UTC
Labels: bug
